# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
 - name: RLSDIR
   value: ./RLSecure
 - name: PURL
   value: Apache/struts2-showcase@2.5.28
 - name: ARTIFACT2SCAN
   value: ./target/struts2-showcase.war

steps:
- task: Maven@3
  displayName: 'Build'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx2048m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: UsePythonVersion@0
  displayName: 'Python Setup'
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  displayName: 'RL Scan'
  inputs:
    targetType: 'inline'  
    script: |
      
      # Install rl-deploy Python package, install rl-secure, then initialize the package store
      python -m pip install --upgrade pip
      pip install rl-deploy
      rl-deploy install $(RLSDIR) --encoded-key=$(rlLicenseKey) --site-key=$(rlSiteKey) --no-tracking
      $(RLSDIR)/rl-secure --version
      $(RLSDIR)/rl-secure init -s $(RLSDIR)

      # Create project & package, then apply custom policy file from SCM
      $(RLSDIR)/rl-secure create -s $(RLSDIR) -p Apache/struts2-showcase
      cp -v ./rl-policy/policy.info $(RLSDIR)/.rl-secure/projects/Apache/packages/struts2-showcase/.package-policy.info

      # Run the scan and generate reports
      $(RLSDIR)/rl-secure scan $(ARTIFACT2SCAN) -s $(RLSDIR) -p $(PURL) --no-tracking
      $(RLSDIR)/rl-secure report -s $(RLSDIR) -p $(PURL) --format cyclonedx,spdx,rl-html,rl-json --output-path $(RLSDIR)
      
      # The following line returns a non-zero exit code if any policy failures are detected by the scan.
      # It can be removed to avoid the task being marked as a failure. 
      $(RLSDIR)/rl-secure status -s $(RLSDIR) -p $(PURL) --return-status

- task: PublishPipelineArtifact@1
  displayName: 'Publish CycloneDX'
  condition: succeededOrFailed()
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/RLSecure/report.cyclonedx.json
    artifactName: CycloneDX-SBOM

- task: PublishPipelineArtifact@1
  displayName: 'Publish SPDX'
  condition: succeededOrFailed()
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/RLSecure/report.spdx.json
    artifactName: SPDX-SBOM

- task: PublishPipelineArtifact@1
  displayName: 'Publish RL-json'
  condition: succeededOrFailed()
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/RLSecure/report.rl.json
    artifactName: ReversingLabs-JSONreport

- task: PublishPipelineArtifact@1
  displayName: 'Publish RL HTML report'
  condition: succeededOrFailed()
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/RLSecure/rl-html
    artifactName: ReversingLabs-HTMLreport
    
